# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\MainWnd.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_PyDaemon(object):
    def setupUi(self, PyDaemon):
        PyDaemon.setObjectName("PyDaemon")
        PyDaemon.resize(600, 450)
        PyDaemon.setMinimumSize(QtCore.QSize(530, 320))
        PyDaemon.setMaximumSize(QtCore.QSize(1920, 1920))
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        font.setPointSize(10)
        PyDaemon.setFont(font)
        PyDaemon.setMouseTracking(False)
        PyDaemon.setWindowOpacity(0.925)
        PyDaemon.setIconSize(QtCore.QSize(32, 32))
        PyDaemon.setDocumentMode(False)
        PyDaemon.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.mainUI = QtWidgets.QWidget(PyDaemon)
        self.mainUI.setObjectName("mainUI")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.mainUI)
        self.verticalLayout.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setSpacing(1)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.status = QtWidgets.QGroupBox(self.mainUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.status.sizePolicy().hasHeightForWidth())
        self.status.setSizePolicy(sizePolicy)
        self.status.setObjectName("status")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.status)
        self.verticalLayout_6.setContentsMargins(12, 0, 0, 0)
        self.verticalLayout_6.setSpacing(1)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.o_currentStatus = QtWidgets.QLabel(self.status)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.o_currentStatus.sizePolicy().hasHeightForWidth())
        self.o_currentStatus.setSizePolicy(sizePolicy)
        self.o_currentStatus.setObjectName("o_currentStatus")
        self.verticalLayout_6.addWidget(self.o_currentStatus)
        self.horizontalLayout_3.addWidget(self.status)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.groupBox_4 = QtWidgets.QGroupBox(self.mainUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_4.sizePolicy().hasHeightForWidth())
        self.groupBox_4.setSizePolicy(sizePolicy)
        self.groupBox_4.setObjectName("groupBox_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_4)
        self.horizontalLayout.setContentsMargins(6, 0, 0, 0)
        self.horizontalLayout.setSpacing(1)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.s_signal_in = QtWidgets.QRadioButton(self.groupBox_4)
        self.s_signal_in.setAutoExclusive(False)
        self.s_signal_in.setObjectName("s_signal_in")
        self.horizontalLayout.addWidget(self.s_signal_in)
        self.s_signal_out = QtWidgets.QRadioButton(self.groupBox_4)
        self.s_signal_out.setAutoExclusive(False)
        self.s_signal_out.setObjectName("s_signal_out")
        self.horizontalLayout.addWidget(self.s_signal_out)
        self.horizontalLayout_3.addWidget(self.groupBox_4)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(1)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.mainUI)
        self.label.setText("")
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.line = QtWidgets.QFrame(self.mainUI)
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.horizontalLayout_2.addWidget(self.line)
        self.groupBox_3 = QtWidgets.QGroupBox(self.mainUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox_3.sizePolicy().hasHeightForWidth())
        self.groupBox_3.setSizePolicy(sizePolicy)
        self.groupBox_3.setObjectName("groupBox_3")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.groupBox_3)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setSpacing(1)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.n_triggerCount = QtWidgets.QLCDNumber(self.groupBox_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.n_triggerCount.sizePolicy().hasHeightForWidth())
        self.n_triggerCount.setSizePolicy(sizePolicy)
        self.n_triggerCount.setMinimumSize(QtCore.QSize(32, 16))
        self.n_triggerCount.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.n_triggerCount.setSmallDecimalPoint(False)
        self.n_triggerCount.setDigitCount(6)
        self.n_triggerCount.setSegmentStyle(QtWidgets.QLCDNumber.Flat)
        self.n_triggerCount.setProperty("value", 0.0)
        self.n_triggerCount.setProperty("intValue", 0)
        self.n_triggerCount.setObjectName("n_triggerCount")
        self.horizontalLayout_8.addWidget(self.n_triggerCount)
        self.horizontalLayout_2.addWidget(self.groupBox_3)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3.setStretch(0, 5)
        self.horizontalLayout_3.setStretch(1, 4)
        self.horizontalLayout_3.setStretch(2, 2)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.groupBox = QtWidgets.QGroupBox(self.mainUI)
        self.groupBox.setFlat(False)
        self.groupBox.setCheckable(False)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setSpacing(1)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.t_Log = QtWidgets.QTableWidget(self.groupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.t_Log.sizePolicy().hasHeightForWidth())
        self.t_Log.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        font.setPointSize(10)
        self.t_Log.setFont(font)
        self.t_Log.setFrameShape(QtWidgets.QFrame.Box)
        self.t_Log.setMidLineWidth(1)
        self.t_Log.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.t_Log.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAsNeeded)
        self.t_Log.setEditTriggers(QtWidgets.QAbstractItemView.DoubleClicked)
        self.t_Log.setTabKeyNavigation(False)
        self.t_Log.setProperty("showDropIndicator", False)
        self.t_Log.setDragDropOverwriteMode(False)
        self.t_Log.setWordWrap(False)
        self.t_Log.setCornerButtonEnabled(True)
        self.t_Log.setRowCount(1)
        self.t_Log.setColumnCount(4)
        self.t_Log.setObjectName("t_Log")
        item = QtWidgets.QTableWidgetItem()
        self.t_Log.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t_Log.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t_Log.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        font.setBold(True)
        font.setWeight(75)
        item.setFont(font)
        self.t_Log.setHorizontalHeaderItem(3, item)
        self.t_Log.horizontalHeader().setCascadingSectionResizes(True)
        self.t_Log.horizontalHeader().setDefaultSectionSize(66)
        self.t_Log.horizontalHeader().setMinimumSectionSize(32)
        self.t_Log.verticalHeader().setVisible(False)
        self.t_Log.verticalHeader().setCascadingSectionResizes(True)
        self.t_Log.verticalHeader().setDefaultSectionSize(19)
        self.t_Log.verticalHeader().setHighlightSections(True)
        self.t_Log.verticalHeader().setMinimumSectionSize(18)
        self.verticalLayout_2.addWidget(self.t_Log)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(8)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_6.addWidget(self.label_3)
        self.i_LogFlite = QtWidgets.QComboBox(self.groupBox)
        self.i_LogFlite.setObjectName("i_LogFlite")
        self.i_LogFlite.addItem("")
        self.i_LogFlite.addItem("")
        self.i_LogFlite.addItem("")
        self.i_LogFlite.addItem("")
        self.horizontalLayout_6.addWidget(self.i_LogFlite)
        self.line_3 = QtWidgets.QFrame(self.groupBox)
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.horizontalLayout_6.addWidget(self.line_3)
        self.i_cleanLog = QtWidgets.QPushButton(self.groupBox)
        self.i_cleanLog.setObjectName("i_cleanLog")
        self.horizontalLayout_6.addWidget(self.i_cleanLog)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem1)
        self.i_LogAutoRoll = QtWidgets.QCheckBox(self.groupBox)
        self.i_LogAutoRoll.setObjectName("i_LogAutoRoll")
        self.horizontalLayout_6.addWidget(self.i_LogAutoRoll)
        self.verticalLayout_2.addLayout(self.horizontalLayout_6)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(self.mainUI)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(1)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.o_Console = QtWidgets.QTextBrowser(self.groupBox_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(self.o_Console.sizePolicy().hasHeightForWidth())
        self.o_Console.setSizePolicy(sizePolicy)
        self.o_Console.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.o_Console.setStyleSheet("QTextEdit { background-color:#1c101b; font-family:\'等距更纱黑体 T SC\',\'monospace\'; font-size:10pt; color: #128f16; white-space:pre}")
        self.o_Console.setFrameShape(QtWidgets.QFrame.Box)
        self.o_Console.setMidLineWidth(1)
        self.o_Console.setDocumentTitle("")
        self.o_Console.setUndoRedoEnabled(False)
        self.o_Console.setLineWrapMode(QtWidgets.QTextEdit.NoWrap)
        self.o_Console.setOverwriteMode(False)
        self.o_Console.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByKeyboard|QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextBrowserInteraction|QtCore.Qt.TextSelectableByKeyboard|QtCore.Qt.TextSelectableByMouse)
        self.o_Console.setObjectName("o_Console")
        self.horizontalLayout_4.addWidget(self.o_Console)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.i_cleanConsole = QtWidgets.QPushButton(self.groupBox_2)
        self.i_cleanConsole.setObjectName("i_cleanConsole")
        self.verticalLayout_3.addWidget(self.i_cleanConsole)
        self.i_copyConsole = QtWidgets.QPushButton(self.groupBox_2)
        self.i_copyConsole.setObjectName("i_copyConsole")
        self.verticalLayout_3.addWidget(self.i_copyConsole)
        self.i_saveConsole = QtWidgets.QPushButton(self.groupBox_2)
        self.i_saveConsole.setObjectName("i_saveConsole")
        self.verticalLayout_3.addWidget(self.i_saveConsole)
        self.i_ConsoleAutoRoll = QtWidgets.QCheckBox(self.groupBox_2)
        self.i_ConsoleAutoRoll.setChecked(True)
        self.i_ConsoleAutoRoll.setObjectName("i_ConsoleAutoRoll")
        self.verticalLayout_3.addWidget(self.i_ConsoleAutoRoll)
        self.horizontalLayout_4.addLayout(self.verticalLayout_3)
        self.verticalLayout_4.addLayout(self.horizontalLayout_4)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setContentsMargins(2, 1, 2, -1)
        self.horizontalLayout_7.setSpacing(2)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.i_cmdType = QtWidgets.QComboBox(self.mainUI)
        self.i_cmdType.setObjectName("i_cmdType")
        self.i_cmdType.addItem("")
        self.i_cmdType.addItem("")
        self.i_cmdType.addItem("")
        self.horizontalLayout_5.addWidget(self.i_cmdType)
        self.i_cmdEditer = QtWidgets.QLineEdit(self.mainUI)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.i_cmdEditer.setFont(font)
        self.i_cmdEditer.setTabletTracking(True)
        self.i_cmdEditer.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.i_cmdEditer.setInputMask("")
        self.i_cmdEditer.setDragEnabled(True)
        self.i_cmdEditer.setClearButtonEnabled(True)
        self.i_cmdEditer.setObjectName("i_cmdEditer")
        self.horizontalLayout_5.addWidget(self.i_cmdEditer)
        self.i_execCMD = QtWidgets.QPushButton(self.mainUI)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.i_execCMD.sizePolicy().hasHeightForWidth())
        self.i_execCMD.setSizePolicy(sizePolicy)
        self.i_execCMD.setObjectName("i_execCMD")
        self.horizontalLayout_5.addWidget(self.i_execCMD)
        self.horizontalLayout_7.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_7.setStretch(0, 7)
        self.verticalLayout.addLayout(self.horizontalLayout_7)
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 9)
        self.verticalLayout.setStretch(2, 6)
        self.verticalLayout.setStretch(3, 1)
        PyDaemon.setCentralWidget(self.mainUI)
        self.menubar = QtWidgets.QMenuBar(PyDaemon)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 600, 18))
        self.menubar.setDefaultUp(False)
        self.menubar.setNativeMenuBar(True)
        self.menubar.setObjectName("menubar")
        self.func = QtWidgets.QMenu(self.menubar)
        self.func.setObjectName("func")
        self.ctrl = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        self.ctrl.setFont(font)
        self.ctrl.setObjectName("ctrl")
        self.about = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        self.about.setFont(font)
        self.about.setObjectName("about")
        PyDaemon.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(PyDaemon)
        self.statusBar.setObjectName("statusBar")
        PyDaemon.setStatusBar(self.statusBar)
        self.reFindeCQ = QtWidgets.QAction(PyDaemon)
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        font.setPointSize(8)
        self.reFindeCQ.setFont(font)
        self.reFindeCQ.setObjectName("reFindeCQ")
        self.sendMSG = QtWidgets.QAction(PyDaemon)
        font = QtGui.QFont()
        font.setFamily("Sarasa Mono T SC")
        font.setPointSize(8)
        self.sendMSG.setFont(font)
        self.sendMSG.setObjectName("sendMSG")
        self.action1 = QtWidgets.QAction(PyDaemon)
        self.action1.setObjectName("action1")
        self.senMSG = QtWidgets.QAction(PyDaemon)
        self.senMSG.setObjectName("senMSG")
        self.func.addAction(self.reFindeCQ)
        self.func.addAction(self.senMSG)
        self.menubar.addAction(self.func.menuAction())
        self.menubar.addAction(self.ctrl.menuAction())
        self.menubar.addAction(self.about.menuAction())

        self.retranslateUi(PyDaemon)
        QtCore.QMetaObject.connectSlotsByName(PyDaemon)

    def retranslateUi(self, PyDaemon):
        _translate = QtCore.QCoreApplication.translate
        PyDaemon.setWindowTitle(_translate("PyDaemon", "MutBot中间层服务程序"))
        self.status.setTitle(_translate("PyDaemon", "运行状态"))
        self.o_currentStatus.setText(_translate("PyDaemon", "{{未知}}"))
        self.groupBox_4.setTitle(_translate("PyDaemon", "通信状态"))
        self.s_signal_in.setText(_translate("PyDaemon", "接收"))
        self.s_signal_out.setText(_translate("PyDaemon", "发送"))
        self.groupBox_3.setTitle(_translate("PyDaemon", "通信计次"))
        self.groupBox.setTitle(_translate("PyDaemon", "运行日志"))
        self.t_Log.setSortingEnabled(True)
        item = self.t_Log.horizontalHeaderItem(0)
        item.setText(_translate("PyDaemon", "序号"))
        item = self.t_Log.horizontalHeaderItem(1)
        item.setText(_translate("PyDaemon", "时间"))
        item = self.t_Log.horizontalHeaderItem(2)
        item.setText(_translate("PyDaemon", "类型"))
        item = self.t_Log.horizontalHeaderItem(3)
        item.setText(_translate("PyDaemon", "内容"))
        self.label_3.setText(_translate("PyDaemon", "显示过滤"))
        self.i_LogFlite.setCurrentText(_translate("PyDaemon", "调试"))
        self.i_LogFlite.setItemText(0, _translate("PyDaemon", "调试"))
        self.i_LogFlite.setItemText(1, _translate("PyDaemon", "信息"))
        self.i_LogFlite.setItemText(2, _translate("PyDaemon", "警告"))
        self.i_LogFlite.setItemText(3, _translate("PyDaemon", "错误"))
        self.i_cleanLog.setText(_translate("PyDaemon", "清屏"))
        self.i_LogAutoRoll.setText(_translate("PyDaemon", "自动滚屏"))
        self.groupBox_2.setTitle(_translate("PyDaemon", "控制台输出"))
        self.o_Console.setHtml(_translate("PyDaemon", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'等距更纱黑体 T SC\',\'monospace\'; font-size:10pt; font-weight:400; font-style:normal;\">\n"
"<p style=\"-qt-paragraph-type:empty; margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><br /></p></body></html>"))
        self.i_cleanConsole.setText(_translate("PyDaemon", "清空内容"))
        self.i_copyConsole.setText(_translate("PyDaemon", "全部复制"))
        self.i_saveConsole.setText(_translate("PyDaemon", "存到文件"))
        self.i_ConsoleAutoRoll.setText(_translate("PyDaemon", "自动滚屏"))
        self.i_cmdType.setCurrentText(_translate("PyDaemon", "SQL操作"))
        self.i_cmdType.setItemText(0, _translate("PyDaemon", "SQL操作"))
        self.i_cmdType.setItemText(1, _translate("PyDaemon", "前端命令"))
        self.i_cmdType.setItemText(2, _translate("PyDaemon", "Py语句"))
        self.i_cmdEditer.setPlaceholderText(_translate("PyDaemon", "Type Code Here..."))
        self.i_execCMD.setText(_translate("PyDaemon", "执行"))
        self.func.setTitle(_translate("PyDaemon", "功能"))
        self.ctrl.setTitle(_translate("PyDaemon", "选项"))
        self.about.setTitle(_translate("PyDaemon", "帮助"))
        self.reFindeCQ.setText(_translate("PyDaemon", "查找前端窗口"))
        self.reFindeCQ.setWhatsThis(_translate("PyDaemon", "重新查找酷Q通信窗口并显示信息"))
        self.sendMSG.setText(_translate("PyDaemon", "发送窗口消息"))
        self.action1.setText(_translate("PyDaemon", "1"))
        self.senMSG.setText(_translate("PyDaemon", "发送窗口消息"))
